version: '3.8'

services:
  webrtc-detection:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - MODE=${MODE:-wasm}
    volumes:
      - ./bench/results:/app/bench/results
      - ./public/models:/app/public/models
    networks:
      - webrtc-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webrtc-net:
    driver: bridge
